JudoMVC/Models/InschrijvingenViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using JudoModelsLibrary;
using MyResources.Deelnemer;

namespace JudoMVC.Models
{
    public class DeelnemerCheckedViewModel
    {
        public int DeelnemerId { get; set; }

        [Required]
        [Display(Name = "LastName", ResourceType = typeof(Resource))]
        public string Familienaam { get; set; }

        [Required]
        [Display(Name = "FirstName", ResourceType = typeof(Resource))]
        public string Voornaam { get; set; }

        [Required]
        [Display(Name = "Gender", ResourceType = typeof(Resource))]
        public Geslacht Geslacht { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0000}", ApplyFormatInEditMode = true)]
        [Display(Name = "BirthYear", ResourceType = typeof(Resource))]
        public int? GeboorteJaar { get; set; }

        [Required]
        public int ClubId { get; set; }

        public bool Assigned { get; set; }
    }
}

JudoMVC/Controllers/DeelnemerController.cs
using System.Web.Mvc;
using JudoModelsLibrary;
using JudoMVC.Models;
using JudoServiceLibrary;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace JudoMVC.Controllers
{
    [Authorize]
    public class DeelnemerController : BaseController
    {
        // GET: Deelnemer
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: Inschrijven/DeelnemersBeheren
        public ActionResult DeelnemersBeheren(int? id, string todo)
        {
            var model = new DeelnemerViewModel();
            //Get current user
            var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var currentUser = manager.FindById(User.Identity.GetUserId());

            //Get club by email from current user
            var clubService = new ClubService();
            var club = clubService.GetClubByEmailWithVerantwoordelijke(currentUser.Email);

            model.ClubId = club.ClubId;

            var deelnemerService = new DeelnemerService();

            if (id.HasValue)
            {
                switch (todo)
                {
                    case "edit":
                        //edit deelnemer
                        var deelnemer = deelnemerService.Read(id.Value);
                        model.DeelnemerId = deelnemer.DeelnemersId;
                        model.Familienaam = deelnemer.Familienaam;
                        model.Voornaam = deelnemer.Voornaam;
                        model.Geslacht = deelnemer.Geslacht;
                        model.GeboorteJaar = deelnemer.GeboorteJaar;
                        ViewBag.todo = "edit";
                        break;
                    case "delete":
                        //delete deelnemer
                        deelnemerService.Delete(id.Value);
                        ViewBag.todo = "delete";
                        break;
                }
            }

            //Fill list with deelnemers
            ViewBag.Deelnemers = deelnemerService.GetDeelnemersFromClub(club.ClubId);

            return View(model);
        }

        //
        // POST: Inschrijven/DeelnemersToevoegen
        [HttpPost]
        public ActionResult DeelnemersBeheren(DeelnemerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var deelnemerService = new DeelnemerService();

                if (model.DeelnemerId != 0)
                {
                    deelnemerService.Update(model.DeelnemerId, model.Familienaam, model.Voornaam, model.GeboorteJaar.GetValueOrDefault(), model.Geslacht);
                }
                else
                {
                    deelnemerService.Create(new Deelnemer { Voornaam = model.Voornaam, Familienaam = model.Familienaam, GeboorteJaar = model.GeboorteJaar.GetValueOrDefault(), Geslacht = model.Geslacht, ClubId = model.ClubId });
                }

                return RedirectToAction("DeelnemersBeheren");
            }
            return View(model);
        }
    }
}

JudoMVC/Controllers/InschrijvingenController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using JudoModelsLibrary;
using JudoMVC.Models;
using JudoMVC.Services;
using JudoServiceLibrary;

namespace JudoMVC.Controllers
{
    [Authorize]
    public class InschrijvingenController : BaseController
    {
        // GET: Inschrijvingen
        public ActionResult Index()
        {
            return View();
        }

        //
        //GET: Inschrijvingen/SelectTornooi
        public ActionResult SelectTornooi()
        {
            var tornooiService = new TornooiService();
            var tornooien = tornooiService.GetTornooienNaDatum(DateTime.Now);
            return View(tornooien);
        }

        //
        //GET: Inschrijvingen/SelectDeelnemers
        public ActionResult SelectDeelnemers(int tornooiId)
        {
            //Get Tornooi
            var tornooiService = new TornooiService();
            var tornooi = tornooiService.ReadWithGemeenteAndLandAndLeeftijdCategories(tornooiId);
            Session["tornooi"] = tornooi;

            //Get Current club
            var userService = new UserService();
            var club = userService.GetCurrentClub();

            //Get Deelnemers
            var deelnemersService = new DeelnemerService();
            var deelnemersChecked = new List<DeelnemerCheckedViewModel>();

            foreach (var categorie in tornooi.TornooiLeeftijdCategories)
            {
                var jongsteJaar = DateTime.Now.Year - categorie.LeeftijdCategorie.LeeftijdBegin;
                var oudsteJaar = DateTime.Now.Year - categorie.LeeftijdCategorie.LeeftijdEinde;
                var deelnemers = deelnemersService.GetDeelnemersFromClubBetweenYears(club.ClubId, jongsteJaar, oudsteJaar);
                foreach (var deelnemer in deelnemers)
                {
                    deelnemersChecked.Add(new DeelnemerCheckedViewModel()
                    {
                        DeelnemerId = deelnemer.DeelnemersId,
                        Voornaam = deelnemer.Voornaam,
                        Familienaam = deelnemer.Familienaam,
                        Geslacht = deelnemer.Geslacht,
                        GeboorteJaar = deelnemer.GeboorteJaar,
                        Assigned = false
                    });
                }
            }
            
            return View(deelnemersChecked);
        }

        //
        //POST: Inschrijvingen/SelectDeelnemers
        [HttpPost]
        public ActionResult SelectDeelnemers(List<DeelnemerCheckedViewModel> deelnemersChecked)
        {
            List<Deelnemer> deelnemers = new List<Deelnemer>();
            var deelnemerService = new DeelnemerService();
            foreach (var deelnemer in deelnemersChecked)
            {
                if(deelnemer.Assigned)
                    deelnemers.Add(deelnemerService.Read(deelnemer.DeelnemerId));
            }
            TempData["deelnemers"] = deelnemers;
            return RedirectToAction("Bevestigen");
        }

        //
        //GET: Inschrijvingen/Bevestigen
        public ActionResult Bevestigen()
        {
            //Get deelnemers
            var deelnemer = (List<Deelnemer>)TempData["deelnemers"];

            //Get Current club
            var userService = new UserService();
            var club = userService.GetCurrentClub();
            ViewBag.Club = club;

            //Get Current Verantwoordelijke
            var verantw = userService.GetCurrentVerantwoordelijke();
            ViewBag.Verantwoordelijke = verantw;

            return View(deelnemer);
        }

        //
        //POST: Inschrijvingen/Bevestigen
        [HttpPost]
        public ActionResult Bevestigen(List<Deelnemer> deelnemers)
        {
            //Email naar verantwoordelijke en naar club
            //Delete session tornooi
            throw new NotImplementedException();
        }
        
    }
}

JudoMVC/Views/Inschrijvingen/Bevestigen.cshtml
@using JudoModelsLibrary
@using Resource = MyResources.Inschrijvingen.Resource
@model List<Deelnemer>


@{
    ViewBag.Title = Resource.Confirmation;
}

<h2>@Resource.Confirmation</h2>

@*Tornooi*@
@{
    var tornooi = Session["tornooi"] as Tornooi;
    if (tornooi != null)
    {
        <section class="Jumbotron">
            <h4>@Resource.Tournament</h4>
            <p><time>@tornooi.Datum.ToShortDateString()</time> @tornooi.TornooiNaam</p>
            <div style="margin-left: 10px; font-size: 12px">
                <p>@tornooi.PlaatsNaam</p>
                    <address>
                        @tornooi.Adres @tornooi.Huisnummer<br/>
                        @tornooi.Gemeente.Postcode @tornooi.Gemeente.Plaats<br/>
                        @tornooi.Gemeente.Land.LandNaam
                    </address>
                <p>
                    <strong>@Resource.Categories</strong>:
                    @{
                        var categories = "";
                        foreach (var tornooiLeeftijdCategorie in tornooi.TornooiLeeftijdCategories)
                        {
                            categories += tornooiLeeftijdCategorie.LeeftijdCategorie.LeeftijdCategorieNaam + " - ";
                        }
                        if (categories.Length > 3)
                        {
                            categories = categories.Remove(categories.Length - 3);
                        }
                    }
                    @categories
                </p>
                <p><strong>@Resource.RegistrationDeadline</strong>: <time>@tornooi.Datum.AddDays(-(tornooi.UitersteInschrijvingVoorAantalDagen)).ToShortDateString()</time></p>
                <p><strong>@Resource.RegistrationFee</strong>: @tornooi.InschrijvingsGeld &euro;</p>
            </div>
        </section>
    }
}

@*Club*@
@{
    var club = (Club)ViewBag.Club;
    <section>
        <h4>@Resource.Club</h4>
        @club.ClubNummer @club.Naam<br/>
        @club.Adres @club.Huisnummer<br/>
        @club.Gemeente.Postcode @club.Gemeente.Plaats<br/>
        @club.Gemeente.Land.LandNaam<br/>
    </section>
}

@*Verantwoordelijke*@
@{
    var verantw = (Verantwoordelijke)ViewBag.Verantwoordelijke;
    <section>
        <h4>@Resource.Manager</h4>
        @verantw.Voornaam @verantw.Familienaam<br/>
        @verantw.Email<br/>
        @verantw.Telefoonnummer<br/>
    </section>
}

@*Deelnemers*@
@using (Html.BeginForm("Bevestigen", "Inschrijvingen", FormMethod.Post, new { @role = "form" }))
{
    <section>
        <h4>@Resource.Participants</h4>
        <ul class="list-group">
            @{ var aantalDeelnemers = Model.Count;}
            @for (int i = 0; i < aantalDeelnemers; i++)
            {
                <li class="list-group-item">
                    @Html.HiddenFor(m => m[i].DeelnemersId)
                    <h4 class="list-group-item-heading">@Model[i].Voornaam @Model[i].Familienaam</h4>
                    <p class="list-group-item-text">@Model[i].GeboorteJaar @Model[i].Geslacht</p>
                </li>
            }
        </ul>
    </section>
    <section>
        @{ var teBetalen = aantalDeelnemers*tornooi.InschrijvingsGeld;}
        <h4>@Resource.PaymentInformation</h4>
        @*******************************************
            Hier komt nog de info voor te betalen!!
            Rekeningnummer, iban, bedrag
            En nog een checkbox voor bevestiging!!
        *******************************************@
    </section>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Bevestigen" />
        </div>
    </div>
    
}

JudoMVC/Views/Inschrijvingen/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

JudoMVC/Views/Inschrijvingen/SelectDeelnemers.cshtml
@using JudoModelsLibrary
@using Resource = MyResources.Inschrijvingen.Resource;
@model List<JudoMVC.Models.DeelnemerCheckedViewModel>

@{
    ViewBag.Title = Resource.SelectParticipants;
}

<h2>@Resource.SelectParticipants</h2>

@{
    var tornooi = Session["tornooi"] as Tornooi;
    if (tornooi != null)
    {
        <div class="jumbotron">
            <p><time>@tornooi.Datum.ToShortDateString()</time> @tornooi.TornooiNaam</p>
            <div style="margin-left: 10px; font-size: 12px">
                @*<p>@tornooi.PlaatsNaam</p>
                <address>
                    @tornooi.Adres @tornooi.Huisnummer<br/>
                    @tornooi.Gemeente.Postcode @tornooi.Gemeente.Plaats<br/>
                    @tornooi.Gemeente.Land.LandNaam
                </address>*@
                <p>
                    <strong>@Resource.Categories</strong>:
                    @{
                        var categories = "";
                        foreach (var tornooiLeeftijdCategorie in tornooi.TornooiLeeftijdCategories)
                        {
                            categories += tornooiLeeftijdCategorie.LeeftijdCategorie.LeeftijdCategorieNaam + " - ";
                        }
                        if (categories.Length > 3)
                        {
                            categories = categories.Remove(categories.Length - 3);
                        }
                    }
                    @categories
                </p>
                <p><strong>@Resource.RegistrationDeadline</strong>: <time>@tornooi.Datum.AddDays(-(tornooi.UitersteInschrijvingVoorAantalDagen)).ToShortDateString()</time></p>
                <p><strong>@Resource.RegistrationFee</strong>: @tornooi.InschrijvingsGeld &euro;</p>
            </div>
        </div>
    }
}



@using (Html.BeginForm("SelectDeelnemers", "Inschrijvingen", FormMethod.Post, new { role = "form" }))
{
    if (Model.Count > 0)
    {
        <h4>@Resource.SelectParticipantsForThisTournament</h4>
        <ul class="list-group checked-list-box">
            @for (int i = 0; i < Model.Count; i++)
            {
                <li class="list-group-item">
                    @Html.CheckBoxFor(m => m[i].Assigned, new {@class = "checkbox", style = "display:none"})
                    @Html.HiddenFor(m => m[i].DeelnemerId)
                    <h4 class="list-group-item-heading">@Html.DisplayTextFor(m => m[i].Voornaam) @Html.DisplayTextFor(m => m[i].Familienaam)</h4>
                    <p class="list-group-item-text">@Html.DisplayTextFor(m => m[i].GeboorteJaar) @Html.DisplayTextFor(m => m[i].Geslacht)</p>
                </li>
            }
        </ul>
        <input type="submit" id="add" class="btn btn-default" value="@Resource.Next"/>
    }
    else
    {
        <h4>@Resource.NoParticipants</h4>
        <p>@Resource.NoParticipantsText</p>
        @Html.ActionLink(Resource.MyParticipants,"DeelnemersBeheren","Deelnemer")
    }

}

@section Scripts {
    @Scripts.Render("~/bundles/checkboxList")
}

JudoMVC/Views/Inschrijvingen/SelectTornooi.cshtml
@using Resource = MyResources.Inschrijvingen.Resource;
@model List<JudoModelsLibrary.Tornooi>

@{
    ViewBag.Title = Resource.SelectTournament;
}

<h2>@Resource.SelectTournament</h2>

<div class="list-group">
    @foreach (var tornooi in Model)
    {
        <a class="list-group-item" href="@Url.Action("SelectDeelnemers", "Inschrijvingen", new {tornooiId=@tornooi.TornooiId})">
            <h4 class="list-group-item-heading"><time>@tornooi.Datum.ToShortDateString()</time> @tornooi.TornooiNaam</h4>
            <div class="list-group-item-text" style="margin-left: 10px">
                <h4 class="list-group-item-text">@tornooi.PlaatsNaam</h4>
                <address>
                    @tornooi.Adres @tornooi.Huisnummer<br />
                    @tornooi.Gemeente.Postcode @tornooi.Gemeente.Plaats<br />
                    @tornooi.Gemeente.Land.LandNaam
                </address>
                <p class="list-group-item-text">
                    <strong>@Resource.Categories</strong>:
                    @{
                        var categories = "";
                        foreach (var tornooiLeeftijdCategorie in tornooi.TornooiLeeftijdCategories)
                        {
                            categories += tornooiLeeftijdCategorie.LeeftijdCategorie.LeeftijdCategorieNaam + " - ";
                        }
                        if (categories.Length > 3)
                        {
                            categories = categories.Remove(categories.Length - 3);
                        }
                    }
                    @categories
                </p>
                <p class="list-group-item-text"><strong>@Resource.RegistrationDeadline</strong>: <time>@tornooi.Datum.AddDays(-(tornooi.UitersteInschrijvingVoorAantalDagen)).ToShortDateString()</time></p>
                <p class="list-group-item-text"><strong>@Resource.RegistrationFee</strong>: @tornooi.InschrijvingsGeld &euro;</p>
            </div>
        </a>
    }
</div>