JudoMVC/Models/TornooiViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using JudoModelsLibrary;
using MyResources.JudoModelsLibrary;

namespace JudoMVC.Models
{
    public class TornooiViewModel
    {
        public int TornooiId { get; set; }

        [Required]
        [StringLength(100)]
        [Display(ResourceType = typeof(Resource), Name = "TournamentName")]
        public string TornooiNaam { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "Date")]
        public DateTime Datum { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "RegistrationDeadline")]
        public int UitersteInschrijvingVoorAantalDagen { get; set; }

        [StringLength(100)]
        [Display(ResourceType = typeof(Resource), Name = "Place")]
        public string PlaatsNaam { get; set; }

        [Required]
        [StringLength(100)]
        [Display(ResourceType = typeof(Resource), Name = "Street")]
        public string Adres { get; set; }

        [Required]
        [StringLength(10)]
        [Display(ResourceType = typeof(Resource), Name = "Number")]
        public string Huisnummer { get; set; }

        [Required]
        [Display(ResourceType = typeof(Resource), Name = "RegistrationFee")]
        [DataType(DataType.Currency)]
        public decimal InschrijvingsGeld { get; set; }

        [Display(ResourceType = typeof(Resource), Name = "Comments")]
        public string Opmerkingen { get; set; }

        public int PostcodeId { get; set; }

        public int ClubId { get; set; }

        public virtual Gemeente Gemeente { get; set; }

        public virtual Club Club { get; set; }

        public virtual ICollection<AssignedCategoriesViewModel> AssignedLeeftijdCategories { get; set; }
    }
}

JudoMVC/Controllers/TornooiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using JudoModelsLibrary;
using JudoMVC.Models;
using JudoMVC.Services;
using JudoServiceLibrary;

namespace JudoMVC.Controllers
{
    [Authorize]
    public class TornooiController : BaseController
    {
        // GET: Tornooi
        public ActionResult Index(int? saved)
        {
            //Get current club
            var userService = new UserService();
            var club = userService.GetCurrentClub();

            //Get Tornooien from club
            var tornooiService = new TornooiService();
            ViewBag.Tornooien = tornooiService.GetTornooiByClub(club.ClubId);

            if (saved != null)
                ViewBag.Saved = saved;
            return View();
        }

        //
        //GET: Tornooi/Toevoegen
        public ActionResult Toevoegen()
        {
            //Fill landen for dropdown
            var landService = new LandService();
            var landen = landService.FindAll();
            ViewBag.Landen = landen;
            var tornooiViewModel = new TornooiViewModel { AssignedLeeftijdCategories = PopulateLeeftijdsCategoriesData(), Datum = DateTime.Now, UitersteInschrijvingVoorAantalDagen = 7};
            return View(tornooiViewModel);
        }

        private static ICollection<AssignedCategoriesViewModel> PopulateLeeftijdsCategoriesData()
        {
            var leeftijdCategoriesService = new  LeeftijdCategorieService();
            var leeftijdcategories = leeftijdCategoriesService.FindAll();
            var assignedLeeftijdCategories = new List<AssignedCategoriesViewModel>();
            var date = new DateTime(DateTime.Now.Year,DateTime.Now.Month, DateTime.Now.Day, 9,0,0);
            foreach (var item in leeftijdcategories)
            {
                assignedLeeftijdCategories.Add(new AssignedCategoriesViewModel
                {
                    LeeftijdCategorieId = item.LeeftijdCategorieId,
                    LeeftijdCategorieNaam = item.LeeftijdCategorieNaam,
                    Assigned = false,
                    StartWeging = date,
                    EindeWeging = date.AddMinutes(30),
                    StartWedstrijden = date.AddMinutes(60)
                });
            }
            return assignedLeeftijdCategories;
        }

        //
        //POST: Tornooi/Toevoegen
        [HttpPost]
        public ActionResult Toevoegen(TornooiViewModel tornooiViewModel)
        {
            var landService = new LandService();
            if (ModelState.IsValid)
            {
                var nieuwTornooi = new Tornooi();
                Land land;
                var gemeente = new Gemeente();
                if (tornooiViewModel.Gemeente.Land.LandId == -99)
                {
                    land = landService.GetLandByName(tornooiViewModel.Gemeente.Land.LandNaam);
                    if (land == null)
                    {
                        land = new Land { LandNaam = tornooiViewModel.Gemeente.Land.LandNaam };
                        gemeente.Land = land;
                    }
                    else
                        gemeente.LandId = land.LandId;
                }
                else
                {
                    land = landService.Read(tornooiViewModel.Gemeente.Land.LandId);
                    gemeente.LandId = land.LandId;
                }

                //check if gemeente exists
                var gemeenteService = new GemeenteService();
                var bestaandeGemeente = gemeenteService.GetGemeenteByPostcodeAndPlaats(tornooiViewModel.Gemeente.Postcode, tornooiViewModel.Gemeente.Plaats, tornooiViewModel.Gemeente.Land.LandId);
                if (bestaandeGemeente == null)
                {
                    gemeente.Postcode = tornooiViewModel.Gemeente.Postcode;
                    gemeente.Plaats = tornooiViewModel.Gemeente.Plaats;
                    nieuwTornooi.Gemeente = gemeente;
                }
                else
                {
                    nieuwTornooi.PostcodeId = bestaandeGemeente.PostcodeId;
                }

                nieuwTornooi.TornooiNaam = tornooiViewModel.TornooiNaam;
                nieuwTornooi.PlaatsNaam = tornooiViewModel.PlaatsNaam;
                nieuwTornooi.Adres = tornooiViewModel.Adres;
                nieuwTornooi.Huisnummer = tornooiViewModel.Huisnummer;
                nieuwTornooi.Datum = tornooiViewModel.Datum;
                nieuwTornooi.UitersteInschrijvingVoorAantalDagen = tornooiViewModel.UitersteInschrijvingVoorAantalDagen;
                nieuwTornooi.InschrijvingsGeld = tornooiViewModel.InschrijvingsGeld;
                nieuwTornooi.Opmerkingen = tornooiViewModel.Opmerkingen;

                //Get current club
                var userService = new UserService();
                var club = userService.GetCurrentClub();

                nieuwTornooi.ClubId = club.ClubId;

                //Checkboxes
                AddOrUpdateCategories(nieuwTornooi, tornooiViewModel.AssignedLeeftijdCategories);
                

                //Save nieuwtornooi
                var tornooiService = new TornooiService();
                bool save = tornooiService.Create(nieuwTornooi);
                
                return RedirectToAction("Index", new {@saved = save});
            }
            //Fill landen for dropdown
            var landen = landService.FindAll();
            ViewBag.Landen = landen;

            return View(tornooiViewModel);
        }

        private static void AddOrUpdateCategories(Tornooi nieuwTornooi, ICollection<AssignedCategoriesViewModel> assignedCategories)
        {
            nieuwTornooi.TornooiLeeftijdCategories = new List<TornooiLeeftijdCategorie>();
            foreach (var assignedCategorie in assignedCategories)
            {
                if (assignedCategorie.Assigned)
                {
                    var leeftijdCatService = new LeeftijdCategorieService();
                    var cat = leeftijdCatService.Read(assignedCategorie.LeeftijdCategorieId);
                    nieuwTornooi.TornooiLeeftijdCategories.Add(new TornooiLeeftijdCategorie
                    {
                        LeeftijdCategorie = cat,
                        StartWeging = assignedCategorie.StartWeging,
                        EindeWeging = assignedCategorie.EindeWeging,
                        StartWedstrijden = assignedCategorie.StartWedstrijden
                    });
                }
            }
        }

        //
        //GET : Tornooi/Verwijder
        public ActionResult Verwijder(int id)
        {
            var tornooiService = new TornooiService();
            tornooiService.Delete(id);
            return RedirectToAction("Index");
        }

        //
        //GET : Tornooi/Wijzig
        public ActionResult Wijzig(int id)
        {
            var tornooiService = new TornooiService();
            var tornooi = tornooiService.ReadWithGemeenteAndLandAndLeeftijdCategories(id);
            var tornooiViewModel = new TornooiViewModel()
            {
                TornooiId = tornooi.TornooiId,
                TornooiNaam = tornooi.TornooiNaam,
                PlaatsNaam = tornooi.PlaatsNaam,
                Adres = tornooi.Adres,
                Huisnummer = tornooi.Huisnummer,
                Datum = tornooi.Datum,
                UitersteInschrijvingVoorAantalDagen = tornooi.UitersteInschrijvingVoorAantalDagen,
                InschrijvingsGeld = tornooi.InschrijvingsGeld,
                Opmerkingen = tornooi.Opmerkingen,
                Gemeente = new Gemeente() { Postcode = tornooi.Gemeente.Postcode, Plaats = tornooi.Gemeente.Plaats, Land = new Land() { LandId = tornooi.Gemeente.Land.LandId, LandNaam = tornooi.Gemeente.Land.LandNaam} }
            };
            
            var leeftijdCategoriesService = new LeeftijdCategorieService();
            var leeftijdcategories = leeftijdCategoriesService.FindAll();
            
            var assignedLeeftijdCategories = new List<AssignedCategoriesViewModel>();
            foreach (var item in leeftijdcategories)
            {
                var item1 = item;
                var cat = tornooi.TornooiLeeftijdCategories.FirstOrDefault(m => m.LeeftijdCategorie.LeeftijdCategorieId == item1.LeeftijdCategorieId);
                var assignedCat = new AssignedCategoriesViewModel()
                {
                    LeeftijdCategorieId = item.LeeftijdCategorieId,
                    LeeftijdCategorieNaam = item.LeeftijdCategorieNaam
                };
                if (cat != null)
                {
                    assignedCat.Assigned = true;
                    assignedCat.StartWeging = cat.StartWeging;
                    assignedCat.EindeWeging = cat.EindeWeging;
                    assignedCat.StartWedstrijden = cat.StartWedstrijden;
                }
                else
                {
                    var date = new DateTime(DateTime.Now.Year,DateTime.Now.Month, DateTime.Now.Day, 9,0,0);
                    assignedCat.Assigned = false;
                    assignedCat.StartWeging = date;
                    assignedCat.EindeWeging = date.AddMinutes(30);
                    assignedCat.StartWedstrijden = date.AddMinutes(60);
                }
                assignedLeeftijdCategories.Add(assignedCat);
            }
            tornooiViewModel.AssignedLeeftijdCategories = assignedLeeftijdCategories;

            //Fill landen for dropdown
            var landService = new LandService();
            var landen = landService.FindAll();
            ViewBag.Landen = landen;

            return View(tornooiViewModel);
        }

        //
        //POST : Tornooi/Wijzig
        [HttpPost]
        public ActionResult Wijzig(TornooiViewModel tornooi)
        {
            if (ModelState.IsValid)
            {
                var tornooiService = new TornooiService();

JudoMVC/Views/Tornooi/Index.cshtml
@using JudoModelsLibrary
@using Resource = MyResources.Tornooi.Resource;

@{
    ViewBag.Title = Resource.ManageTournaments;
}

<h2>@Resource.ManageTournaments</h2>
@*Messages*@

@if (ViewBag.Saved != null)
{
    <div class="row temp-msg">
        <div class="col-md-4">
            <div class="form-group">
                @if (ViewBag.Saved == 0)
                {
                    <div class="alert alert-danger" role="alert">
                        @Resource.TournamentSavedError
                    </div>
                }
                else if (ViewBag.Saved == -1)
                {
                    <div class="alert alert-warning" role="alert">
                        @Resource.NothingChanged
                    </div>
                }
                else
                {
                    <div class="alert alert-success" role="alert">
                        @Resource.TournamentSaved
                    </div>
                }
                
            </div>
        </div>
    </div>
}

@*TornooienList*@
    
    @if (ViewBag.Tornooien != null)
    {
        var tornooien = (List<Tornooi>)ViewBag.Tornooien;
        <div class="list-group">
            @foreach (var tornooi in tornooien)
            {
                <div class="list-group-item">
                    <a href="@Url.Action("Verwijder","Tornooi", new {id=tornooi.TornooiId})" class="badge">@Resource.Delete</a>
                    <a href="@Url.Action("Wijzig","Tornooi", new {id=tornooi.TornooiId})" class="badge">@Resource.Edit</a>
                    <h4 class="list-group-item-heading"><time>@tornooi.Datum.ToShortDateString()</time> @tornooi.TornooiNaam</h4>
                    <div class="list-group-item-text" style="margin-left: 10px">
                        <h4 class="list-group-item-text">@tornooi.PlaatsNaam</h4>
                        <address>
                            @tornooi.Adres @tornooi.Huisnummer<br/>
                            @tornooi.Gemeente.Postcode @tornooi.Gemeente.Plaats<br/>
                            @tornooi.Gemeente.Land.LandNaam
                        </address>
                        
                        <p class="list-group-item-text"><strong>@Resource.Categories</strong>:
                            @{
                                var categories = "";
                                foreach (var tornooiLeeftijdCategorie in tornooi.TornooiLeeftijdCategories)
                                {
                                    categories += tornooiLeeftijdCategorie.LeeftijdCategorie.LeeftijdCategorieNaam + " - ";
                                }
                                if (categories.Length > 3)
                                {
                                    categories = categories.Remove(categories.Length - 3);
                                }
                            }
                            @categories
                        </p>
                        <p class="list-group-item-text"><strong>@Resource.RegistrationDeadline</strong>: <time>@tornooi.Datum.AddDays(-(tornooi.UitersteInschrijvingVoorAantalDagen)).ToShortDateString()</time></p>
                        <p class="list-group-item-text"><strong>@Resource.RegistrationFee</strong>: @tornooi.InschrijvingsGeld &euro;
                        <p class="list-group-item-text"><strong>@Resource.Comments</strong>: @tornooi.Opmerkingen</p>
                    </div>
                </div>
            }
        </div>
    }

@*Buttons*@
@Html.ActionLink(Resource.AddTournament, "Toevoegen", "Tornooi", new { @class = "btn btn-default" })

@section Scripts {
    @Scripts.Render("~/bundles/custom")
}

JudoMVC/Views/Tornooi/Toevoegen.cshtml
@using JudoModelsLibrary
@using JudoMVC.Helper
@using JudoMVC.Models
@using Resource = MyResources.Tornooi.Resource;
@using RDP = MyResources.DatePicker.Resource;
@model TornooiViewModel

@Styles.Render("~/Content/datetimepicker")

@{
    ViewBag.Title = Resource.AddTournament;
}

<h2>@Resource.AddTournament</h2>

@using (Html.BeginForm("Toevoegen", "Tornooi", FormMethod.Post, new {role = "form"}))
{
    <h4>@Resource.CreateANewTournament</h4>
    <hr/>

    @Html.ValidationSummary("", new { @class= "text-danger"})
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.TornooiNaam, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.TornooiNaam, new {@class = "form-control", placeholder = @Html.DisplayNameFor(m => m.TornooiNaam), autofocus = "autofocus"})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.Datum, new {@class = "control-label"})
                @{
                    string[] dayNamesMin = {RDP.Su, RDP.Mo, RDP.Tu, RDP.We, RDP.Th, RDP.Fr, RDP.Sa};
                    string[] monthNames = {RDP.January, RDP.February, RDP.March, RDP.April, RDP.May, RDP.June, RDP.July, RDP.August, RDP.September, RDP.October, RDP.November, RDP.December};
                    uint startDayOfWeek = uint.Parse(RDP.StartDayOfWeek);
                }
                @Html.JQueryUI().DatepickerFor(m => m.Datum, new {@class = "form-control datepicker", placeholder = @Html.DisplayNameFor(m => m.Datum), type="date"}).FirstDay(startDayOfWeek).DayNamesMin(dayNamesMin).MonthNames(monthNames).MinDate(0).DefaultDate(0)
            </div>
        </div>
        <div class="col-md-3 maxwidth">
            <div class="form-group">
                @Html.LabelFor(m => m.UitersteInschrijvingVoorAantalDagen, new {@class = "control-label"})
                <div class="input-group">
                    @Html.EditorFor(m => m.UitersteInschrijvingVoorAantalDagen, new { @htmlAttributes = new { @class = "form-control minwidth" }})
                    <div class="input-group-addon">@Resource.DaysForTournamentDate</div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.PlaatsNaam, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.PlaatsNaam, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.PlaatsNaam)})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Adres, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.Adres, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Adres)})
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Huisnummer, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.Huisnummer, new {@class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Huisnummer)})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Postcode, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.Gemeente.Postcode, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Gemeente.Postcode)})
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Plaats, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.Gemeente.Plaats, new {@class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Gemeente.Plaats)})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Land.LandId, new {@class = "control-label", id = "LabelLandId"})
                @{var landen = (List<Land>) ViewBag.Landen;
                    landen.Add(new Land {LandId = -99, LandNaam = Resource.AddOtherCountry});}
                @Html.DropDownListFor(m => m.Gemeente.Land.LandId, new SelectList(landen, "LandId", "LandNaam"), "", new {@class = "form-control", id = "Landen"})
            </div>
        </div>
        <div class="col-md-3 hidden" id="LandNaam">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Land.LandNaam, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.Gemeente.Land.LandNaam, new {@class = "form-control", id = "textBoxLandNaam", placeholder = @Html.DisplayNameFor(m => m.Gemeente.Land.LandNaam)})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.Label(Resource.AgeCategories)
                @Html.EditorFor(m => m.AssignedLeeftijdCategories, new {@class = "form-control"})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.InschrijvingsGeld, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.InschrijvingsGeld, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.InschrijvingsGeld) })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Opmerkingen, new {@class = "control-label"})
                @Html.TextAreaFor(m => m.Opmerkingen, new {@class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Opmerkingen), style="height: 100px"})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                <input type="submit" id="add" class="btn btn-default" value="@Resource.Add" />
            </div>
        </div>
    </div>
}

<div class="hidden">
    @{ var culture = CultureHelper.GetCurrentCulture();}
    <label id="culture">@culture</label>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/datetimepicker")
    @Scripts.Render("~/bundles/custom")
}

JudoMVC/Views/Tornooi/Wijzig.cshtml
@model JudoMVC.Models.TornooiViewModel
@using JudoModelsLibrary
@using JudoMVC.Helper
@using Resource = MyResources.Tornooi.Resource;
@using RDP = MyResources.DatePicker.Resource;

@Styles.Render("~/Content/datetimepicker")
@{
    ViewBag.Title = Resource.ChangeTournament;
}

<h2>@Resource.ChangeTournament</h2>

@using (Html.BeginForm("Wijzig", "Tornooi", FormMethod.Post, new { role = "form" }))
{
    <h4>@Resource.ChangeTournamentDetails</h4>
    <hr />

    @Html.ValidationSummary("", new { @class = "text-danger" })   
    @Html.HiddenFor(m=>m.TornooiId) 
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.TornooiNaam, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.TornooiNaam, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.TornooiNaam), autofocus = "autofocus" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.Datum, new {@class = "control-label"})
                @{
                    string[] dayNamesMin = {RDP.Su, RDP.Mo, RDP.Tu, RDP.We, RDP.Th, RDP.Fr, RDP.Sa};
                    string[] monthNames = {RDP.January, RDP.February, RDP.March, RDP.April, RDP.May, RDP.June, RDP.July, RDP.August, RDP.September, RDP.October, RDP.November, RDP.December};
                    uint startDayOfWeek = uint.Parse(RDP.StartDayOfWeek);
                }
                @Html.JQueryUI().DatepickerFor(m => m.Datum, new {@class = "form-control datepicker", placeholder = @Html.DisplayNameFor(m => m.Datum)}).FirstDay(startDayOfWeek).DayNamesMin(dayNamesMin).MonthNames(monthNames)
            </div>
        </div>
        <div class="col-md-3 maxwidth">
            <div class="form-group">
                @Html.LabelFor(m => m.UitersteInschrijvingVoorAantalDagen, new { @class = "control-label" })
                <div class="input-group">
                    @Html.EditorFor(m => m.UitersteInschrijvingVoorAantalDagen, new { @htmlAttributes = new { @class = "form-control minwidth" } })
                    <div class="input-group-addon">@Resource.DaysForTournamentDate</div>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.PlaatsNaam, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.PlaatsNaam, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.PlaatsNaam), autofocus = "autofocus" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Adres, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Adres, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Adres), autofocus = "autofocus" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Huisnummer, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Huisnummer, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Huisnummer), autofocus = "autofocus" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Postcode, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Gemeente.Postcode, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Gemeente.Postcode), autofocus = "autofocus" })
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Plaats, new { @class = "control-label" })
                @Html.TextBoxFor(m => m.Gemeente.Plaats, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Gemeente.Plaats), autofocus = "autofocus" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Land.LandId, new {@class = "control-label", id = "LabelLandId"})
                @{var landen = (List<Land>) ViewBag.Landen;
                    landen.Add(new Land {LandId = -99, LandNaam = Resource.AddOtherCountry});}
                @Html.DropDownListFor(m => m.Gemeente.Land.LandId, new SelectList(landen, "LandId", "LandNaam"), "", new {@class = "form-control", id = "Landen"})
            </div>
        </div>
        <div class="col-md-3 hidden" id="LandNaam">
            <div class="form-group">
                @Html.LabelFor(m => m.Gemeente.Land.LandNaam, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.Gemeente.Land.LandNaam, new {@class = "form-control", id = "textBoxLandNaam", placeholder = @Html.DisplayNameFor(m => m.Gemeente.Land.LandNaam)})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.Label(Resource.AgeCategories)
                @Html.EditorFor(m => m.AssignedLeeftijdCategories, new {@class = "form-control"})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.InschrijvingsGeld, new {@class = "control-label"})
                @Html.TextBoxFor(m => m.InschrijvingsGeld, new {@class = "form-control", placeholder = @Html.DisplayNameFor(m => m.InschrijvingsGeld)})
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(m => m.Opmerkingen, new { @class = "control-label" })
                @Html.TextAreaFor(m => m.Opmerkingen, new { @class = "form-control", placeholder = @Html.DisplayNameFor(m => m.Opmerkingen), style = "height: 100px" })
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <input type="submit" class="btn btn-default" value="@Resource.SaveChanges"/>
                <a class="btn btn-default" href="@Url.Action("Index", "Tornooi")">@Resource.Cancel</a>
            </div>
        </div>
    </div>
}

<div class="hidden">
    @{ var culture = CultureHelper.GetCurrentCulture();}
    <label id="culture">@culture</label>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/moment")
    @Scripts.Render("~/bundles/datetimepicker")
    @Scripts.Render("~/bundles/custom")
}